# Generated by Django 4.1.12 on 2023-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
