# Generated by Django 4.1.12 on 2023-11-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_imagine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagine',
        ),
    ]
